const quotes = [
    "A vida é um presente; aproveite cada momento como um tesouro.",
    "Cada dia é uma nova oportunidade para fazer algo incrível.",
    "Não conte os dias, faça os dias contarem.",
    "A felicidade não está no destino, mas na jornada.",
    "A vida é uma aventura ousada ou não é nada.",
    "Se você quer mudar o mundo, comece por mudar a si mesmo.",
    "A vida é feita de escolhas; escolha ser feliz.",
    "Cada desafio é uma chance de crescimento e aprendizado.",
    "O melhor ainda está por vir. Mantenha-se firme.",
    "A vida é breve. Faça cada momento valer a pena.",
    "Acredite que você pode e você já está no meio do caminho.",
    "Encontre alegria nas pequenas coisas e celebre cada conquista.",
    "Viva o presente com gratidão e um coração aberto.",
    "Sua vida é sua mensagem para o mundo; faça-a positiva e inspiradora.",
    "A vida é um reflexo dos seus pensamentos; pense grande e positivo.",
    "Não tenha medo de começar de novo. É uma nova chance para ser melhor.",
    "A vida é um mosaico de momentos; aproveite cada peça.",
    "Cada amanhecer é uma nova chance para reescrever sua história.",
    "Seja a mudança que você deseja ver no mundo.",
    "A vida é uma dança; aprenda a se mover ao ritmo dela.",
    "Nunca subestime o poder de um sorriso e uma palavra gentil.",
    "Você é mais forte do que imagina e capaz de conquistar muito mais.",
    "Valorize cada momento, pois cada um é único e precioso.",
    "A vida é uma jornada, não um destino. Aproveite a viagem.",
    "O verdadeiro sucesso é encontrar alegria na vida cotidiana.",
    "Seus sonhos são possíveis. Acredite e siga em frente.",
    "A vida não é sobre esperar a tempestade passar, mas aprender a dançar na chuva.",
    "A gratidão transforma o que temos em suficiente e mais.",
    "Cada dia é uma página em branco; escreva uma história incrível.",
    "A vida é feita de escolhas. Escolha a alegria, a esperança e a coragem.",
    "Abrace a vida com entusiasmo e veja as maravilhas se revelarem.",
    "A vida é um presente; trate-a com carinho e sabedoria.",
    "Não se preocupe com o que os outros pensam; viva a sua verdade.",
    "A vida é uma aventura; abrace o desconhecido com coragem e curiosidade.",
    "Siga em frente com fé e confiança. A vida recompensa os ousados.",
    "A vida é uma tela em branco; pinte-a com suas cores mais vibrantes.",
    "Os desafios são oportunidades disfarçadas para crescer e evoluir.",
    "A vida é uma jornada pessoal; celebre suas vitórias e aprenda com os desafios.",
    "Valorize cada instante; o tempo é o bem mais precioso que temos.",
    "A vida é curta demais para não viver plenamente e com paixão.",
    "Sorria para a vida e ela sorrirá de volta para você.",
    "A vida é feita de momentos; faça cada um deles inesquecível.",
    "Viva com propósito e cada dia será uma realização.",
    "Cada dificuldade é uma chance para descobrir sua força interior.",
    "Não tenha medo de ser único; sua individualidade é seu maior presente.",
    "A vida é sobre criar memórias, não apenas acumular coisas.",
    "Acreditar em si mesmo é o primeiro passo para transformar seus sonhos em realidade.",
    "A vida é bela; mesmo nos momentos difíceis, há sempre uma razão para sorrir.",
    "A vida é uma jornada que se torna mais rica com cada experiência vivida.",
    "Seja grato pelo que você tem; há beleza em cada situação.",
    "Você tem o poder de criar uma vida cheia de felicidade e realização.",
    "Cada dia é uma nova oportunidade para ser a melhor versão de si mesmo.",
    "A vida é uma coleção de momentos preciosos; torne-os memoráveis e significativos.",
    "Seja ousado em seus sonhos e generoso em seus atos de bondade.",
    "A vida é uma dádiva; valorize cada momento e aproveite ao máximo.",
    "Acredite na magia dos novos começos e na força que há dentro de você.",
    "Cada desafio é uma chance de se tornar mais forte e mais sábio.",
    "A vida é uma viagem; aprecie a paisagem e as pessoas ao longo do caminho.",
    "Siga seu coração e ele sempre o levará para onde você precisa estar.",
    "Você é o autor da sua própria história; escreva-a com coragem e paixão.",
    "A vida é feita de pequenas alegrias; encontre-as e celebre-as.",
    "O melhor ainda está por vir; mantenha-se esperançoso e motivado.",
    "A vida é preciosa; viva-a com intensidade e gratidão.",
    "Cada dia é uma nova chance para recomeçar e fazer melhor.",
    "A vida é uma canção; cante-a com alegria e amor.",
    "Acredite em sua força interior e você pode conquistar qualquer coisa.",
    "A vida é feita de momentos; faça com que cada um deles seja significativo.",
    "A vida é uma oportunidade para criar e viver momentos inesquecíveis.",
    "Siga seu coração e você encontrará a verdadeira felicidade.",
    "Cada desafio é uma chance de brilhar e mostrar sua verdadeira força.",
    "A vida é um presente; aproveite-a ao máximo e faça a diferença.",
    "A vida é uma jornada de descobertas; abrace cada uma delas com entusiasmo.",
    "Você tem o poder de criar uma vida incrível; acredite nisso e faça acontecer.",
    "Cada dia é uma nova chance para recomeçar e fazer melhor.",
    "A vida é uma dança; encontre seu ritmo e dance com alegria.",
    "Cada dia é uma nova chance para fazer a diferença; aproveite-a.",
    "A vida é feita de momentos; faça com que cada um deles seja especial.",
    "Não importa onde você esteja, sempre há uma razão para ser grato.",
    "A vida é uma oportunidade; aproveite-a para ser a melhor versão de si mesmo.",
    "A vida é uma celebração; viva-a com entusiasmo e alegria.",
    "Cada dia é uma nova chance para fazer a diferença e ser feliz.",
    "A vida é cheia de possibilidades; abra-se para elas e veja onde elas o levam.",
    "Você é a mudança que o mundo precisa; abrace seu poder e faça a diferença.",
    "A vida é um dom; aproveite-a ao máximo e faça a diferença.",
    "A vida é uma jornada de descobertas; abrace cada uma delas com entusiasmo.",
    "Você tem o poder de criar uma vida incrível; acredite nisso e faça acontecer."
];

function showRandomQuote() {
    if (quotes.length === 0) {
        document.getElementById('quote').textContent = "Nenhuma frase disponível.";
        return;
    }
    const randomIndex = Math.floor(Math.random() * quotes.length);
    document.getElementById('quote').textContent = quotes[randomIndex];
}
